modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="xsurvive"
version="1.18.2-1.0"
displayName="XSurvive"
credits="Thanks for downloading my Mod"
authors="Luis"
#displayURL="https://github.com/Luis-st/Forge-XSurvive/issues"
description='''

Have a lot of fun when playing
XSurvive Development Team
'''

[[dependencies.xsurvive]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.xsurvive]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.xsurvive]]
modId="xbackpack"
mandatory=true
versionRange="[1.18.2-1.5,)"
ordering="BEFORE"

[[dependencies.xsurvive]]
modId="xores"
mandatory=true
versionRange="[1.18.2-1.3,)"
ordering="BEFORE"