modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="xsurvive"
version="1.19-1.3"
displayName="XSurvive"
credits="Thanks for downloading my Mod"
authors="Luis"
#displayURL="https://github.com/Luis-st/Forge-XSurvive/issues"
description='''
XSurvive is a life balancing mod

Have a lot of fun when playing
XSurvive Development Team
'''

[[dependencies.xsurvive]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.xsurvive]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.xsurvive]]
modId="xbackpack"
mandatory=true
versionRange="[1.19-2.1,)"
ordering="BEFORE"

[[dependencies.xsurvive]]
modId="xores"
mandatory=true
versionRange="[1.19-1.8,)"
ordering="BEFORE"